//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcePresentation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePresentation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourcePresentation", typeof(ResourcePresentation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Kulüp Seçiniz--.
        /// </summary>
        public static string cmbKulupDefaultValue {
            get {
                return ResourceManager.GetString("cmbKulupDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm alanları doldurunuz!.
        /// </summary>
        public static string KulupGuncelleFalse {
            get {
                return ResourceManager.GetString("KulupGuncelleFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulüp Güncellemesi Yapıldı..
        /// </summary>
        public static string KulupGuncelleTrue {
            get {
                return ResourceManager.GetString("KulupGuncelleTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm alanları doldurunuz (ID Hariç)!.
        /// </summary>
        public static string KulupKaydetFalse {
            get {
                return ResourceManager.GetString("KulupKaydetFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulüp Kaydı Yapıldı..
        /// </summary>
        public static string KulupKaydetTrue {
            get {
                return ResourceManager.GetString("KulupKaydetTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulüp Listesi.
        /// </summary>
        public static string KulupListesi {
            get {
                return ResourceManager.GetString("KulupListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulüp silme işlemi yapılamadı!.
        /// </summary>
        public static string KulupSilFalse {
            get {
                return ResourceManager.GetString("KulupSilFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kulüp silindi..
        /// </summary>
        public static string KulupSilTrue {
            get {
                return ResourceManager.GetString("KulupSilTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci ID, Ort. ve Durum hariç tüm alanları doldurunuz!.
        /// </summary>
        public static string NotGuncelleFalse {
            get {
                return ResourceManager.GetString("NotGuncelleFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not girme alanları 0 ile 100 arasında olmalıdır!.
        /// </summary>
        public static string NotGuncelleFalse2 {
            get {
                return ResourceManager.GetString("NotGuncelleFalse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Güncellemesi Yapıldı..
        /// </summary>
        public static string NotGuncelleTrue {
            get {
                return ResourceManager.GetString("NotGuncelleTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Listesi.
        /// </summary>
        public static string NotListesi {
            get {
                return ResourceManager.GetString("NotListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KALDI.
        /// </summary>
        public static string NotPass {
            get {
                return ResourceManager.GetString("NotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm alanları doldurunuz!.
        /// </summary>
        public static string OgrenciGuncelleFalse {
            get {
                return ResourceManager.GetString("OgrenciGuncelleFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Güncellemesi Yapıldı..
        /// </summary>
        public static string OgrenciGuncelleTrue {
            get {
                return ResourceManager.GetString("OgrenciGuncelleTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm alanları doldurunuz (ID Hariç)!.
        /// </summary>
        public static string OgrenciKaydetFalse {
            get {
                return ResourceManager.GetString("OgrenciKaydetFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Kaydı Yapıldı..
        /// </summary>
        public static string OgrenciKaydetTrue {
            get {
                return ResourceManager.GetString("OgrenciKaydetTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci Listesi.
        /// </summary>
        public static string OgrenciListesi {
            get {
                return ResourceManager.GetString("OgrenciListesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci silme işlemi yapılamadı!.
        /// </summary>
        public static string OgrenciSilFalse {
            get {
                return ResourceManager.GetString("OgrenciSilFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğrenci silindi..
        /// </summary>
        public static string OgrenciSilTrue {
            get {
                return ResourceManager.GetString("OgrenciSilTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇTİ.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string TrueString {
            get {
                return ResourceManager.GetString("TrueString", resourceCulture);
            }
        }
    }
}
