//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTblNotlar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTblNotlar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourceTblNotlar", typeof(ResourceTblNotlar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURUM.
        /// </summary>
        public static string DURUM {
            get {
                return ResourceManager.GetString("DURUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRID.
        /// </summary>
        public static string OGRENCI_ID {
            get {
                return ResourceManager.GetString("OGRENCI_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRENCIID.
        /// </summary>
        public static string OGRENCIID {
            get {
                return ResourceManager.GetString("OGRENCIID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORTALAMA.
        /// </summary>
        public static string ORTALAMA {
            get {
                return ResourceManager.GetString("ORTALAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJE.
        /// </summary>
        public static string PROJE {
            get {
                return ResourceManager.GetString("PROJE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINAV1.
        /// </summary>
        public static string SINAV_1 {
            get {
                return ResourceManager.GetString("SINAV_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINAV2.
        /// </summary>
        public static string SINAV_2 {
            get {
                return ResourceManager.GetString("SINAV_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINAV3.
        /// </summary>
        public static string SINAV_3 {
            get {
                return ResourceManager.GetString("SINAV_3", resourceCulture);
            }
        }
    }
}
