//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStoredProcedure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStoredProcedure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utility.ResourceStoredProcedure", typeof(ResourceStoredProcedure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULUPEKLE.
        /// </summary>
        public static string KULUP_EKLE {
            get {
                return ResourceManager.GetString("KULUP_EKLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULUPGUNCELLE.
        /// </summary>
        public static string KULUP_GUNCELLE {
            get {
                return ResourceManager.GetString("KULUP_GUNCELLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULUPLISTESI.
        /// </summary>
        public static string KULUP_LISTELE {
            get {
                return ResourceManager.GetString("KULUP_LISTELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KULUPSIL.
        /// </summary>
        public static string KULUP_SIL {
            get {
                return ResourceManager.GetString("KULUP_SIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTGUNCELLE.
        /// </summary>
        public static string NOT_GUNCELLE {
            get {
                return ResourceManager.GetString("NOT_GUNCELLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTLISTESI.
        /// </summary>
        public static string NOT_LISTELE {
            get {
                return ResourceManager.GetString("NOT_LISTELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRENCIEKLE.
        /// </summary>
        public static string OGRENCI_EKLE {
            get {
                return ResourceManager.GetString("OGRENCI_EKLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRENCIGUNCELLE.
        /// </summary>
        public static string OGRENCI_GUNCELLE {
            get {
                return ResourceManager.GetString("OGRENCI_GUNCELLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRENCILISTESI.
        /// </summary>
        public static string OGRENCI_LISTELE {
            get {
                return ResourceManager.GetString("OGRENCI_LISTELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGRENCISIL.
        /// </summary>
        public static string OGRENCI_SIL {
            get {
                return ResourceManager.GetString("OGRENCI_SIL", resourceCulture);
            }
        }
    }
}
